[lan]
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python3"
#vpn_server ansible_host=159.89.224.195 ansible_user=root
[wireguard]
lan

[wireguard:vars]
ansible_user=root
