 - hosts: lan
   any_errors_fatal: true
   become: true
   vars_files:
     - vars/default.yml
   pre_tasks:
     - name: Atualizar repositórios
       apt:
         update_cache: yes
       changed_when: False
   tasks:
     - include: tasks/packages.yml
     - include: tasks/users.yml
     - include: tasks/cron.yml
     - include: tasks/docker.yml
#   roles: 
#    - { role: prepare }
#    - { role: wireguard }
