---
- fail: 
    msg: "Only Debian supported for now"
  when: ansible_distribution != 'Ubuntu'

- name: Instalar Wireguard
  apt:
    name: wireguard
    state: present
    update_cache: yes

- name: Apt upgrade (Debian)
  apt:
    name: wireguard
    update_cache: yes
    state: latest

- name: Install dependencies (Debian)
  apt:
    name: ['linux-headers-{{ ansible_kernel }}', 'software-properties-common']
    state: present

- name: Enable net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    reload: yes
    state: present


