---
dist: bionic
language: python

cache:
  directories:
  - /home/travis/.vagrant.d/boxes

install:
# Instalar libvrt & KVM (REF: https://github.com/alvistack/ansible-role-virtualbox/blob/master/.travis.yml)
- sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils 
- sudo apt-get install -y ruby-dev ruby-libvirt libxslt-dev libxml2-dev zlib1g-dev libvirt-dev zlib1g-dev

# Download Vagrant & Instalar
- sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
- sudo dpkg -i vagrant_2.2.14_x86_64.deb
- sudo rm vagrant_2.2.14_x86_64.deb

# O Vagrant foi instalado corretamente?
- vagrant --version

# Instalar os plugins do Vagrant
- sudo vagrant plugin install vagrant-libvirt

script:
- bash shell
