#!/bin/bash

instalar_requerimentos(){
    echo "Atualizar repositórios e instalar os requerimentos para rodar o neoricalex..."
    sudo apt update
    sudo apt install -y \
        autoconf \
        automake \
        build-essential \
        git \
        make \
        tmux
}

iniciar_local(){
    if [ ! -f "src/neoricalex.o" ] ; then
        instalar_requerimentos
        autoreconf --install
        ./configure
        make
        #make distcheck
    fi

    src/neoricalex
}

usuario="$(whoami)@$(hostname | cut -d . -f 1-2)"
if [ "$usuario" == "neo@desktop" ]; then

    if [ -d "src/vps" ] ; then
        cd src/vps
        echo "Atualizar o github:neoricalex/vps..."
        git add .
        git commit -m "Atualização Automática via bash shell"
        git push origin master
        cd ../..
    fi
   
    iniciar_local

    cd src
    cat *.log
    cd ..

    echo "Atualizar o github:neoricalex/neoricalex..."
    git add .
    git commit -m "Atualização Automática via bash shell"
    git push origin master

    #sudo docker tag nfdos/core/rootfs neoricalex/nfdos
    #sudo docker login
    #sudo docker push neoricalex/nfdos
    #sudo docker logout

    # sudo apt install trash-cli -y
    # trash-list
    # trash-restore foo
    
    # wget https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar
    # sudo apt install default-jre default-jdk -y
    # java -jar tools/bfg-1.14.0.jar --strip-blobs-bigger-than 100M .
    # git gc --prune=now --aggressive

    #docker rmi nfdos/core/rootfs:latest
    #sudo rm -rf nfdos/core/rootfs
    #sudo apt autoremove -y
    #docker run --rm --name neoricalex nfdos/core/rootfs

    #chmod +x compilar.sh
    #./compilar.sh
    #chmod +x upload_cloud.sh
    #./upload_cloud.sh
    
else
    iniciar_local
fi
