#!/bin/bash

instalar_requerimentos(){
    echo "Atualizar repositórios e instalar requerimentos..."
    sudo apt update
    sudo apt install -y \
        autoconf \
        build-essential \
        git \
        make \
        tmux

}

iniciar_local(){
    if [ ! -f "src/neoricalex.o" ] ; then
        instalar_requerimentos
        autoreconf --install
        ./configure
        make
        #make distcheck
    fi

    src/neoricalex
}

usuario="$(whoami)@$(hostname | cut -d . -f 1-2)"
if [ "$usuario" == "neo@desktop" ]; then

    cd src/vps
    git add .
    git commit -m "Atualização Automática via bash shell"
    git push origin master
    cd ../..
   
    iniciar_local

    cd src
    cat *.log
    #rm *.log
    cd ..

    git add .
    git commit -m "Atualização Automática via bash shell"
    #git push origin master

    #sudo docker tag nfdos/core/rootfs neoricalex/nfdos
    #sudo docker login
    #sudo docker push neoricalex/nfdos
    #sudo docker logout
else
    iniciar_local
fi
