Vagrant.configure('2') do |config|

    config.vm.provision "shell" do |s|
        s.inline = %Q(/usr/bin/env    \
          TRAVIS=#{ENV['TRAVIS']})
    end
    
    if ENV['TRAVIS'] == '1'
         travis = true
    else
        travis = false
    end

    config.vm.provider :virtualbox do |virtualbox, override|
        virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		virtualbox.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
		#virtualbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
		virtualbox.customize ["modifyvm", :id, "--nestedpaging", "on"]
		virtualbox.name		= "VPS_DEV"
		virtualbox.memory	= "4096"
		virtualbox.cpus   	= "3"
        #override.vm.box = 'Ubuntu'
        #override.vm.box_url = 'https:///'
    end

    if travis == false
        config.vm.define :VPS_DEV do |vps_dev|
            vps_dev.vm.define "VPS_DEV"
            vps_dev.vm.box = "neoricalex/nfdos"
            vps_dev.vm.box_version = "0.4.4"
            vps_dev.vm.hostname  = "vps-dev"
            vps_dev.ssh.username = "neo"
            vps_dev.ssh.password = "neoricalex"
            vps_dev.disksize.size = "100GB"
            vps_dev.vm.provision :shell,
            path: "vagrant-libs/bootstrap.sh"
        end
    end

    if travis == true
        config.vm.define :VPS_TRAVIS do |vps_travis|
            vps_travis.vm.hostname = 'vps_travis'
            vps_travis.vm.define "VPS_BASE"
            vps_travis.vm.box = "generic/ubuntu1804"
            vps_travis.vm.boot_timeout = 1800
            vps_travis.disksize.size = "100GB"
        end
    end
end