- name: Instalar o cron job (ansible-pull)
  cron:
    user: ansible
    name: "Provisionar o Ansible"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -i src/vps/nfdos/desktop/ansible/inventory.ini -C master -U https://github.com/neoricalex/neoricalex.git src/vps/nfdos/desktop/ansible/local.yml > /dev/null"
